apiVersion: v1
kind: Service
metadata:
  name: resterapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
  selector:
    app: resterapp
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: resterapp
spec:
  selector:
    matchLabels:
      app: resterapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resterapp
    spec:
      containers:
      - image: davelabine/resterapp
        name: resterapp
        env:
        - name: DB_URL
          value: "jdbc:mysql://mysql.default.svc.cluster.local/resterapp_dev?useSSL=false"
        - name: DB_UNAME
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: username
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password