# Default values for resterapp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

# MySQL values
# Disable persistence for now since it complicates db setup like root pw

mysql:
  mysqlRootPassword: password
  mysqlDatabase: resterapp_dev
  persistence:
    enabled: false
  service:
    type: NodePort
    port: 3306
    nodePort: 32000

  

