apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-app.fullname" . }}
  labels:
    app: {{ include "student-app.name" . }}
    chart: {{ include "student-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    app: {{ include "student-app.name" . }}
    release: {{ .Release.Name }}
