apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "resterapp-svc.fullname" . }}
  labels:
    app: {{ include "resterapp-svc.name" . }}
    chart: {{ include "resterapp-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "resterapp-svc.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: {{ include "resterapp-svc.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_HBM2DDL_AUTO
            value: "{{ .Values.db_hbm2ddl_auto }}"
          - name: DB_URL
            value: "jdbc:mysql://{{ .Release.Name }}-mysql.default.svc.cluster.local/resterapp_dev?useSSL=false"
          - name: DB_UNAME
            value: root
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mysql
                key: mysql-root-password


