export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export type FETCH_STUDENTS = typeof FETCH_STUDENTS;

export const FILTER_STUDENTS = 'FILTER_STUDENTS';
export type FILTER_STUDENTS = typeof FILTER_STUDENTS;

export const ADD_STUDENT = 'ADD_STUDENT';
export type ADD_STUDENT = typeof ADD_STUDENT;