# Default values for resterapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

resterappsvc:
  name: resterapp-svc
  replicaCount: 1
  db_hbm2ddl_auto: create
  image:
    repository: davelabine/resterapp
    tag: latest
    pullPolicy: IfNotPresent  
  service:
    type: NodePort
    port: 8080
    # Comment this out when using service types other than NodePort
    nodePort: 30800

studentapp:
  name: student-app
  replicaCount: 1
  image:
    repository: davelabine/student-app
    tag: latest
    pullPolicy: IfNotPresent  
  service:
    type: NodePort
    port: 3000
    # Comment this out when using service types other than NodePort
    nodePort: 30000

# MySQL values

mysql:
  # mysqlRootPassword: password
  mysqlDatabase: resterapp_dev
  # Disable persistence for now since it complicates db setup like root pw
  persistence:
    enabled: false
  service:
    type: NodePort
    port: 3306
    nodePort: 32000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}