package com.davelabine.resterapp.platform.api.model;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.util.Random;

/**
 * Created by davidl on 9/29/16.
 */
public class Student {

    @Getter
    @Setter
    protected String key;

    @Getter
    @Setter
    protected String id;

    @Getter
    @Setter
    protected String name;

    @Getter
    @Setter
    protected BlobLocation photo;

    public Student() {}
    public Student(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public static Student randomStudent() {
        String name = randomChoice(givenNames) + " " + randomChoice(surnames);
        String id = Integer.toString(rand.nextInt(999999));
        return new Student(id, name);
    }

    private static Random rand = new java.util.Random();

    // Names generated by http://random-name-generator.info/
    private static String[] givenNames = new String[] {
            "Ada", "Albert", "Alexandra", "Alfredo", "Alice", "Allen", "Andre", "Angelica",
            "Anna", "Anthony", "Antonio", "Ashley", "Audrey", "Autumn", "Beatrice",
            "Benjamin", "Billy", "Bobby", "Bradley", "Brian", "Bryant", "Candace",
            "Carole", "Carrie", "Christine", "Claire", "Clifford", "Clint", "Clyde", "Cory",
            "Dale", "Danielle", "Daryl", "Dave", "Delia", "Devin", "Doris", "Douglas", "Eddie",
            "Ella", "Erica", "Erika", "Eva", "Frank", "Gayle", "George", "Georgia",
            "Geraldine", "Gina", "Gwen", "Hector", "Homer", "Irene", "James",
            "Jamie", "Jeremiah", "Joann", "Josefina", "Juan", "Karen", "Kenneth",
            "Laurie", "Lee", "Leland", "Leroy", "Levi", "Lewis", "Lillian",
            "Lillie", "Lorenzo", "Louise", "Lucas", "Lynn", "Marc", "Marcella",
            "Marlon", "Marvin", "Micheal", "Miranda", "Miriam", "Misty", "Naomi",
            "Natasha", "Nelson", "Oliver", "Patrick", "Pete", "Rafael", "Randall", "Raul",
            "Rebecca", "Reginald", "Robert", "Roger", "Ruby", "Rufus", "Sabrina", "Sean",
            "Steven", "Stuart", "Terence", "Terry", "Van", "Velma", "Vincent",
            "Wanda", "Willard", "Winifred"
    };
    private static String[] surnames = new String[] {
            "Adkins", "Aguilar", "Anderson", "Armstrong", "Arnold", "Bailey",
            "Banks", "Barrett", "Bates", "Bennett", "Bowers", "Bradley", "Brown",
            "Bryant", "Buchanan", "Bush", "Butler", "Cain", "Carlson", "Carroll",
            "Cummings", "Diaz", "Doyle", "Duncan", "Dunn", "Fernandez", "Foster",
            "Fowler", "Fox", "Francis", "French", "Garrett", "Gill", "Glover",
            "Goodwin", "Gordon", "Grant", "Griffin", "Gross", "Guerrero", "Hale",
            "Harvey", "Holland", "Ingram", "Jacobs", "James", "LaBine", "Lamb", "Lowe",
            "Lucas", "Mann", "Marshall", "Martin", "Martinez", "May", "Mcdaniel",
            "McKenna", "Mendoza", "Meyer", "Moody", "Moreno", "Nelson", "Nichols",
            "Norton", "Obrien", "Osborne", "Padilla", "Page", "Parks", "Parsons", "Payne",
            "Pearson", "Powell", "Reese", "Reeves", "Reyes", "Reynolds",
            "Richardson", "Rios", "Ross", "Rochefort", "Roulston", "Russell", "Saunders",
            "Sharp", "Simon", "Smith", "Steele", "Stephens", "Stokes", "Summers", "Thomas",
            "Thompson", "Tyler", "Wagner", "Ward", "Washington", "Watkins",
            "Watson", "Weber", "West", "Willis", "Wilson", "Young", "Zimmerman"
    };

    private static String randomChoice(String[] names) {
        return names[rand.nextInt(names.length)];
    }

}
