apiVersion: v1
kind: Service
metadata:
  name: student-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: student-app
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: student-app
spec:
  selector:
    matchLabels:
      app: student-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - image: davelabine/student-app
        name: student-app